name: dbt_project
version: '1.0'
profile: dbt_project

model-paths: ["models"]

models:
  dbt_project:
    staging:
      +schema: staging
    marts:
      +schema: marts
      growth:
        +materialized: table
      differences:
        +materialized: view
