default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 
      user: 
      password: 
      port: 5432
      dbname: 
      schema: public  
      threads: 
      keepalives_idle: 
